---
# MongoDB container setup
- name: Create MongoDB data directory
  file:
    path: "{{ mongo_data_path }}"
    state: directory
    mode: '0755'
  tags:
    - mongodb
    - setup

- name: Pull MongoDB Docker image
  docker_image:
    name: "{{ mongo_image }}"
    source: pull
  tags:
    - mongodb
    - images

- name: Run MongoDB container
  docker_container:
    name: "{{ mongo_container_name }}"
    image: "{{ mongo_image }}"
    state: started
    restart_policy: always
    network_mode: "{{ mongo_network }}"
    ports:
      - "{{ mongo_port }}:27017"
    volumes:
      - "{{ mongo_data_path }}:/data/db"
    env:
      MONGO_INITDB_DATABASE: yolo
  tags:
    - mongodb
    - container

- name: Wait for MongoDB to be available
  wait_for:
    host: localhost
    port: "{{ mongo_port }}"
    delay: 10
    timeout: 60
  tags:
    - mongodb
    - verify
