apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: week5-project
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http
  selector:
    app: week5-project
    tier: frontend
