apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: yolo-app
  labels:
    app: week5-project
    tier: database
spec:
  clusterIP: None
  ports:
  - port: 3306
    name: mysql
  selector:
    app: week5-project
    tier: database
