apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-app-deployment
  namespace: yolo-app
  labels:
    app: yolo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yolo-app
  template:
    metadata:
      labels:
        app: yolo-app
    spec:
      containers:
        - name: yolo-app-container
          image: kimberlynangira/week5-backend:latest # Replace with your actual image name
          ports:
            - containerPort: 5000 # Make sure this is the port your app listens on
          env:
            - name: DATABASE_HOST
              value: "mongodb-service" # Connect to the MongoDB service
            - name: DATABASE_PORT
              value: "27017"       # Default MongoDB port
          #  Remove any MySQL-specific environment variables here
          #  For example, remove these lines or similar:
          #  - name: DATABASE_USER
          #    value: "your_mysql_user"
          #  - name: DATABASE_PASSWORD
          #    value: "your_mysql_password"
          #  - name: DATABASE_NAME
          #    value: "your_mysql_db"
