version: "3.8"
services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    image: kimberlynangira/yolo-client:1.0.0
    container_name: yolo-client
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - yolo-network
    restart: unless-stopped
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: kimberlynangira/yolo-backend:1.0.0
    container_name: yolo-backend
    ports:
      - "8080:80"
    environment:
      - RAILS_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/yolo
    command: bash -c "rails server -b 0.0.0.0 -p 80"
    depends_on:
      - mongodb
    networks:
      - yolo-network
    restart: unless-stopped
  
  mongodb:
    image: mongo:4.4
    container_name: yolo-mongodb
    volumes:
      - mongo-data:/data/db
    networks:
      - yolo-network
    restart: unless-stopped

networks:
  yolo-network:
    driver: bridge

volumes:
  mongo-data:
    name: yolo-mongo-data
