# Use an official, Node runtine as a parent im
FROM node:14 AS  
# Set the working directory in the container
WORKDIR /usr/src/app
# Copy the package. json and package-lock. json
COPY package*.json ./
# Install application dependencies
RUN npm install
# Copy the rest of the application code to the
COPY • .
#Add multi-stage build
FROM alpine: 3.16.7
WORKDIR /app
RUN apk update && apk add -no-cache nodejs na
COPY -fron-build /usr/src/app /app
# Expose the port the app runs on
EXPOSE 5000
# Define the command to run your app
CMD ["node", "server.js"]
