# In ecommerce-ansible/roles/backend/tasks/main.yml
---
- name: Install backend dependencies
  npm:
    path: "{{ backend_dir }}"
    state: present
  become: yes

- name: Create backend Dockerfile
  copy:
    dest: "{{ backend_dir }}/Dockerfile"
    content: |
      FROM node:16-alpine
      WORKDIR /app
      COPY package*.json ./
      RUN npm install
      COPY . .
      EXPOSE {{ backend_port }}
      CMD ["npm", "start"]
    mode: '0644'
  become: yes

- name: Check if backend image exists
  command: docker images -q backend:latest
  register: backend_image_exists
  changed_when: false
  become: yes

- name: Build backend Docker image
  command: docker build -t backend:latest {{ backend_dir }}
  become: yes
  when: backend_image_exists.stdout == ""

- name: Check if backend container exists
  command: docker ps -a -q -f name={{ backend_container_name }}
  register: backend_container_exists
  changed_when: false
  become: yes

- name: Remove existing backend container
  command: docker rm -f {{ backend_container_name }}
  become: yes
  when: backend_container_exists.stdout != ""

- name: Run backend container
  command: >
    docker run -d 
    --name {{ backend_container_name }} 
    --restart always 
    --network {{ docker_network_name }} 
    -p {{ backend_port }}:{{ backend_port }} 
    -e MONGO_URI=mongodb://{{ mongo_username }}:{{ mongo_password }}@{{ mongo_container_name }}:{{ mongo_container_port }}/{{ mongo_db_name }}
    backend:latest
  become: yes

- name: Check backend container status
  command: docker inspect -f {% raw %}'{{.State.Status}}'{% endraw %} {{ backend_container_name }}
  register: backend_status
  changed_when: false
  become: yes

- name: Show backend container status
  debug:
    msg: "Backend container status: {{ backend_status.stdout }}"
