apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: yolo
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo
      tier: backend
  template:
    metadata:
      labels:
        app: yolo
        tier: backend
    spec:
      containers:
      - name: backend
        image: week5-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb-0.mongodb-service:27017/yolo"
        livenessProbe:  # Add this section
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        readinessProbe: # Add this section
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: yolo
    tier: backend
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
