apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv # A unique name for your Persistent Volume
  labels:
    app: mongodb-pv # Add a label to match with the PVC selector
spec:
  accessModes: [ "ReadWriteOnce" ] # Only one pod can mount this volume at a time
  capacity:
    storage: 10Gi # The size of the persistent volume
  hostPath:
    path: /data/mongodb # The path on the Minikube node where the data will be stored
    type: DirectoryOrCreate # Creates the directory if it doesn't exist
