apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: yolo-app
  labels:
    app: mongodb
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongodb
