apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: yolo-app
  labels:
    app: yolo
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: yolo
    tier: backend
