apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: yolo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: kimberlynangira/week5-backend:latest  #  <--- IMPORTANT: Use a specific tag if you have one
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb-0.mongodb-service:27017/yolodb"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: yolo-app
spec:
  selector:
    app: backend
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
